# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traffic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'traffic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtraffic.proto\x12\x07traffic\"g\n\x0eProcessRequest\x12\x14\n\x0cvideo_source\x18\x01 \x01(\t\x12\x14\n\x0clanes_config\x18\x02 \x01(\t\x12\x14\n\x0cweights_path\x18\x03 \x01(\t\x12\x13\n\x0bsave_output\x18\x04 \x01(\x08\"Y\n\x05Rates\x12$\n\x03vpm\x18\x01 \x03(\x0b\x32\x17.traffic.Rates.VpmEntry\x1a*\n\x08VpmEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\";\n\nPhaseTimes\x12\r\n\x05verde\x18\x01 \x01(\x01\x12\x10\n\x08\x61marillo\x18\x02 \x01(\x01\x12\x0c\n\x04rojo\x18\x03 \x01(\x01\"\x92\x01\n\x04Tick\x12\x0c\n\x04\x66\x61se\x18\x01 \x01(\t\x12\x0e\n\x06\x65stado\x18\x02 \x01(\t\x12\x12\n\nt_restante\x18\x03 \x01(\x05\x12\x1d\n\x05rates\x18\x04 \x01(\x0b\x32\x0e.traffic.Rates\x12$\n\x07tiempos\x18\x05 \x01(\x0b\x32\x13.traffic.PhaseTimes\x12\x13\n\x0b\x66rame_index\x18\x06 \x01(\x05\"c\n\x07Summary\x12\x17\n\x0f\x64uracion_sesion\x18\x01 \x01(\x01\x12$\n\x07tiempos\x18\x02 \x01(\x0b\x32\x13.traffic.PhaseTimes\x12\x19\n\x11output_video_path\x18\x03 \x01(\t\"`\n\x0fProcessResponse\x12\x1d\n\x04tick\x18\x01 \x01(\x0b\x32\r.traffic.TickH\x00\x12#\n\x07summary\x18\x02 \x01(\x0b\x32\x10.traffic.SummaryH\x00\x42\t\n\x07payload\"\x07\n\x05\x45mpty\")\n\x06Health\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x85\x01\n\x0eTrafficService\x12\x43\n\x0cProcessVideo\x12\x17.traffic.ProcessRequest\x1a\x18.traffic.ProcessResponse0\x01\x12.\n\x0bHealthCheck\x12\x0e.traffic.Empty\x1a\x0f.traffic.Healthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATES_VPMENTRY']._loaded_options = None
  _globals['_RATES_VPMENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSREQUEST']._serialized_start=26
  _globals['_PROCESSREQUEST']._serialized_end=129
  _globals['_RATES']._serialized_start=131
  _globals['_RATES']._serialized_end=220
  _globals['_RATES_VPMENTRY']._serialized_start=178
  _globals['_RATES_VPMENTRY']._serialized_end=220
  _globals['_PHASETIMES']._serialized_start=222
  _globals['_PHASETIMES']._serialized_end=281
  _globals['_TICK']._serialized_start=284
  _globals['_TICK']._serialized_end=430
  _globals['_SUMMARY']._serialized_start=432
  _globals['_SUMMARY']._serialized_end=531
  _globals['_PROCESSRESPONSE']._serialized_start=533
  _globals['_PROCESSRESPONSE']._serialized_end=629
  _globals['_EMPTY']._serialized_start=631
  _globals['_EMPTY']._serialized_end=638
  _globals['_HEALTH']._serialized_start=640
  _globals['_HEALTH']._serialized_end=681
  _globals['_TRAFFICSERVICE']._serialized_start=684
  _globals['_TRAFFICSERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
